version: '2'

services:
  app:
    build: .
    image: cloudflared-web
    container_name: cloudflared-web
    environment:
      WEBUI_PORT: 1111
    ports:
      - target: 1111
        published: 1111
        protocol: tcp
    volumes:
      - ./config:/config
      - ../app/backend:/var/app/backend
      - ../app/frontend:/var/app/frontend
    tty: true
    stdin_open: true
