name: publish
on: [push]
jobs:
  publish-cloudflared-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the cloudflared Docker image
      run: |
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64,linux/armhf -t ghcr.io/wisdomsky/casaos-cloudflared:latest -t ghcr.io/wisdomsky/casaos-cloudflared:2023.7.3 --push .
      #run: |
      #      docker build . --tag ghcr.io/wisdomsky/casaos-cloudflared:latest
      #      docker run ghcr.io/wisdomsky/casaos-cloudflared:latest
      #      docker push ghcr.io/wisdomsky/casaos-cloudflared:latest